---
name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Check whether secrets exist
        if: github.ref == 'refs/heads/main'
        id: secret-presence
        run: |
          [ ! -z "${{ secrets.CXNG_GHCR_PAT }}" ] && echo "::set-output name=CXNG_GHCR_PAT::true"
          exit 0

      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run tests
        run: mvn -B test --file pom.xml

      - name: Build Docker image
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: username/repository:latest

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CXNG_GHCR_PAT }}

      - name: Build Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/catenax-ng/product-vcissuer/vcissuer:latest
