---
name: Release - Image

on:
  pull_request:
    types: [closed ]
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # see https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
      id-token: read
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v2

      # RELEASE VERSION
      -
        name: Extract version from branch name (for release branches)
        if: startsWith(github.event.pull_request.head.ref, 'release/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}

          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
      -
        name: Extract version from branch name (for hotfix branches)
        if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#hotfix/}

          echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
      -
        name: Output release version
        run: |
          echo "::set-output name=RELEASE_VERSION::${{ env.RELEASE_VERSION }}"

      # BUILD & TEST
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run tests
        run: mvn -B test --file pom.xml

      # DOCKER PUSH
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/product-vcissuer/vcissuer:latest,ghcr.io/${{ env.OWNER_LC }}/product-vcissuer/vcissuer:${{ env.RELEASE_VERSION }}
